// Auto-generated by scripts/generate-gallery-index.mjs
// Do not edit manually

export const categories = [
  { id: 'all', label: { zh: '全部', en: 'All' } },
  { id: 'design', label: { zh: '已上传平面设计', en: 'Uploaded Design' } },
  { id: 'dynamic', label: { zh: '动态', en: 'Dynamic' } },
]

export const projects = [
  {
    "id": "design-0000",
    "slug": "0000",
    "title": {
      "zh": "0000",
      "en": "0000"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/0000/AHLT0003-0.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/0000/AHLT0003-0.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/0000/AHLT0003-1.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/0000/AHLT0003-2.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/0000/AHLT0003-3.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/0000/AHLT0003-4.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/0000/AHLT0003-0.webp",
      "fallback": "/media/gallery/design/0000/AHLT0003-0.webp"
    }
  },
  {
    "id": "design-00002",
    "slug": "00002",
    "title": {
      "zh": "00002",
      "en": "00002"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/00002/捆绑摩托车-02.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/00002/捆绑摩托车-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/00002/捆绑摩托车-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/00002/捆绑摩托车.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/00002/捆绑摩托车-02.webp",
      "fallback": "/media/gallery/design/00002/捆绑摩托车-02.webp"
    }
  },
  {
    "id": "design-0004",
    "slug": "0004",
    "title": {
      "zh": "0004",
      "en": "0004"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/0004/xstrap主页.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/0004/xstrap主页.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/0004/xstrap主页02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/0004/xstrap主页.webp",
      "fallback": "/media/gallery/design/0004/xstrap主页.webp"
    }
  },
  {
    "id": "design-16019",
    "slug": "16019",
    "title": {
      "zh": "16019",
      "en": "16019"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16019/16019.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16019/16019.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16019/16019.webp",
      "fallback": "/media/gallery/design/16019/16019.webp"
    }
  },
  {
    "id": "design-16031",
    "slug": "16031",
    "title": {
      "zh": "16031",
      "en": "16031"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16031/16031-01.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16031/16031-01.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-04.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-05.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-06.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-07.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16031/16031-08.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16031/16031-01.webp",
      "fallback": "/media/gallery/design/16031/16031-01.webp"
    }
  },
  {
    "id": "design-16094",
    "slug": "16094",
    "title": {
      "zh": "16094",
      "en": "16094"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16094/16094-02.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16094/16094-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094-04.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094-05.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094-07.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094-08.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16094/16094.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16094/16094-02.webp",
      "fallback": "/media/gallery/design/16094/16094-02.webp"
    }
  },
  {
    "id": "design-16095",
    "slug": "16095",
    "title": {
      "zh": "16095",
      "en": "16095"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16095/16095-01.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16095/16095-01.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-04.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-05.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-06.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095-07.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16095/16095.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16095/16095-01.webp",
      "fallback": "/media/gallery/design/16095/16095-01.webp"
    }
  },
  {
    "id": "design-16096",
    "slug": "16096",
    "title": {
      "zh": "16096",
      "en": "16096"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16096/16096-01.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16096/16096-01.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096-04.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096-05.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096-06.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/16096/16096.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16096/16096-01.webp",
      "fallback": "/media/gallery/design/16096/16096-01.webp"
    }
  },
  {
    "id": "design-16097",
    "slug": "16097",
    "title": {
      "zh": "16097",
      "en": "16097"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/16097/16097.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/16097/16097.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/16097/16097.webp",
      "fallback": "/media/gallery/design/16097/16097.webp"
    }
  },
  {
    "id": "design-28",
    "slug": "28",
    "title": {
      "zh": "28",
      "en": "28"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/28/28件套带模板-01.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/28/28件套带模板-01.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-03.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-04.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-05.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-06.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-07.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/28/28件套带模板-08.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/28/28件套带模板-01.webp",
      "fallback": "/media/gallery/design/28/28件套带模板-01.webp"
    }
  },
  {
    "id": "design-32031",
    "slug": "32031",
    "title": {
      "zh": "32031",
      "en": "32031"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/32031/32031-0.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/32031/32031-0.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/32031/32031.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/32031/32031-0.webp",
      "fallback": "/media/gallery/design/32031/32031-0.webp"
    }
  },
  {
    "id": "design-35002",
    "slug": "35002",
    "title": {
      "zh": "35002",
      "en": "35002"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/35002/35002,35003,35004,35005.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/35002/35002,35003,35004,35005.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/35002/35002-0.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/35002/35002,35003,35004,35005.webp",
      "fallback": "/media/gallery/design/35002/35002,35003,35004,35005.webp"
    }
  },
  {
    "id": "design-61817",
    "slug": "61817",
    "title": {
      "zh": "61817",
      "en": "61817"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": "/media/gallery/design/61817/61817-01.webp",
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [
      {
        "src": "/media/gallery/design/61817/61817-01.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/61817-02.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/61817-03jpg.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/61817-04jpg.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/61817-05jpg.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/61817.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      },
      {
        "src": "/media/gallery/design/61817/IMG_3952.webp",
        "width": 1500,
        "height": 1500,
        "aspectRatio": 1
      }
    ],
    "previewVideo": null,
    "thumb": {
      "src": "/media/gallery/design/61817/61817-01.webp",
      "fallback": "/media/gallery/design/61817/61817-01.webp"
    }
  },
  {
    "id": "design-Video editing",
    "slug": "Video editing",
    "title": {
      "zh": "Video editing",
      "en": "Video editing"
    },
    "summary": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "description": {
      "zh": "XSTRAP",
      "en": "XSTRAP"
    },
    "group": "design",
    "coverSrc": null,
    "coverDimensions": {
      "width": 1500,
      "height": 1500,
      "aspectRatio": 1
    },
    "gallery": [],
    "previewVideo": "/media/gallery/design/Video editing/preview.mp4",
    "thumb": {
      "src": null,
      "fallback": null
    }
  }
]
